store: store
tardis_bin: assets/tardis
metron_endpoint: 127.0.0.1:3457
log_level: debug
log_file: groot.log
create:
  exclude_image_from_quota: true
  skip_layer_validation: true
  with_clean: true
  clean_log_file: groot.clean.log
  without_mount: false
  disk_limit_size_bytes: 524288000
  insecure_registries: []
clean:
  threshold_bytes: 266683506688
init:
  store_size_bytes: 266683506688
  owneruser: ""
  ownergroup: ""
